1) 2.1.2.1: When fulfilled, a promise: must not transition to any other state. trying to fulfill then immediately reject:
     TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleRejected (index.js:59:16)
      at PromiseA.reject (index.js:79:10)
      at Context.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.1.2.js:37:11)

  2) 2.1.2.1: When fulfilled, a promise: must not transition to any other state. trying to fulfill then reject, delayed:
     Uncaught TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleRejected (index.js:59:16)
      at PromiseA.reject (index.js:79:10)
      at Timeout._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.1.2.js:54:15)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  3) 2.1.3.1: When rejected, a promise: must not transition to any other state. already-rejected:
     Uncaught TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleRejected (index.js:59:16)
      at PromiseA.reject (index.js:79:10)
      at Timeout._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.1.2.js:72:15)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  4) 2.1.3.1: When rejected, a promise: must not transition to any other state. trying to reject then immediately fulfill:
     TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleFulfilled (index.js:51:16)
      at PromiseA.resolve (index.js:65:10)
      at Context.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.1.3.js:37:11)

  5) 2.2.2: If `onFulfilled` is a function, 2.2.2.2: it must not be called before `promise` is fulfilled fulfilled after a delay:
     Uncaught TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleFulfilled (index.js:51:16)
      at PromiseA.resolve (index.js:65:10)
      at Timeout._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.1.3.js:54:15)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  6) 2.2.2: If `onFulfilled` is a function, 2.2.2.3: it must not be called more than once. trying to fulfill a pending promise more than once, immediately:
     Error: done() called multiple times
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:66:9)
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:56:5)
      at Object.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:13:1)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

  7) 2.2.2: If `onFulfilled` is a function, 2.2.2.3: it must not be called more than once. trying to fulfill a pending promise more than once, immediately:
     Error: done() called multiple times
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:66:9)
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:56:5)
      at Object.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:13:1)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

  8) 2.2.3: If `onRejected` is a function, 2.2.3.1: it must be called after `promise` is rejected, with `promise`â€™s rejection reason as its first argument. eventually-rejected:
     Uncaught TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleFulfilled (index.js:51:16)
      at PromiseA.resolve (index.js:65:10)
      at Timeout._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.2.2.js:90:19)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  9) 2.2.3: If `onRejected` is a function, 2.2.3.2: it must not be called before `promise` is rejected rejected after a delay:
     Uncaught TypeError: Cannot assign to read only property 'value' of object '#<PromiseA>'
      at PromiseA.handleFulfilled (index.js:51:16)
      at PromiseA.resolve (index.js:65:10)
      at Timeout._onTimeout (node_modules/promises-aplus-tests/lib/tests/2.1.3.js:72:15)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  10) 2.2.3: If `onRejected` is a function, 2.2.3.3: it must not be called more than once. trying to reject a pending promise more than once, immediately:
     Error: done() called multiple times
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:66:9)
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:56:5)
      at Object.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:13:1)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

  11) 2.2.3: If `onRejected` is a function, 2.2.3.3: it must not be called more than once. trying to reject a pending promise more than once, immediately:
     Error: done() called multiple times
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:66:9)
      at Suite.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:56:5)
      at Object.<anonymous> (node_modules/promises-aplus-tests/lib/tests/2.2.3.js:13:1)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)

  12) 2.2.3: If `onRejected` is a function, 2.2.3.3: it must not be called more than once. Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
      at processImmediate (internal/timers.js:439:21)

  13) 2.3.2: If `x` is a promise, adopt its state 2.3.2.1: If `x` is pending, `promise` must remain pending until `x` is fulfilled or rejected. via return from a rejected promise:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  14) 2.3.2: If `x` is a promise, adopt its state 2.3.2.2: If/when `x` is fulfilled, fulfill `promise` with the same value. `x` is eventually-fulfilled via return from a rejected promise:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  15) 2.2.7: `then` must return a promise: `promise2 = promise1.then(onFulfilled, onRejected)` 2.2.7.2: If either `onFulfilled` or `onRejected` throws an exception `e`, `promise2` must be rejected with `e` as the reason. The reason is `false` eventually-fulfilled:
     Error: timeout of 200ms exceeded. Ensure the done() callback is being called in this test.
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)